# Modifed from https://github.com/flathub/net.veloren.veloren/raw/master/net.veloren.veloren.yaml

name: Auto update

env:
  BUILDER_TOOLS_URL: https://github.com/catsout/flatpak-builder-tools
  # newer version in `yarn2` branch causes error
  BUILDER_TOOLS_BRANCH: afc69116fcb909c1786cd49a0650f914515877ef
  APPLICATION_URL: https://github.com/standardnotes/app.git
  APPLICATION_ID: org.standardnotes.standardnotes
  APPLICATION_NAME: standardnotes
  YQ_VERSION: "v4.6.1"
  YQ_BINARY: yq_linux_amd64
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache

on:
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup flatpak-builder-tools
        run: |
          pipx install "git+${BUILDER_TOOLS_URL}@${BUILDER_TOOLS_BRANCH}#subdirectory=node"

      # Rather than track the tip of a branch
      - name: Get the current tag
        run: |
          set -ev
          sudo apt-get install jq

          TAG=`yq e ".modules.[] | select(.name == \"${APPLICATION_NAME}\") | .sources.[] | select(.url == \"${APPLICATION_URL}\") | .tag" ${APPLICATION_ID}.yml`
          echo ${TAG}
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Download corresponding application repository
        run: |
          git clone --depth=1 -b ${TAG} \
                       ${APPLICATION_URL} \
                       ${XDG_CACHE_HOME}/${APPLICATION_ID}

      - name: Run update
        run: |
          set -ev

          flatpak-node-generator --electron-node-headers yarn ${XDG_CACHE_HOME}/${APPLICATION_ID}/yarn.lock

          if [[ -n "$(git status --porcelain --untracked-files=no | grep --invert-match generated-sources.json)" ]]; then
              echo "there are no changes";
              exit 0;
          fi
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "Workflow trigger"
          git add generated-sources.json
          git commit -m "update generated-sources.json"
          git push https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}
